language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
jobs:
  include:
    - stage: cover
      node_js: "12"
      script:
        - npm run cover
        - npm run coverage